# Generated by Django 5.0.4 on 2024-05-15 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.doctor'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.shift'),
        ),
    ]
