# Generated by Django 5.0.4 on 2024-05-16 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0004_service_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='service_images/'),
        ),
    ]
