# Generated by Django 5.0.4 on 2024-07-04 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0005_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
