# Generated by Django 5.0.4 on 2024-05-15 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0001_initial'),
        ('medical', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalconsultation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.patient'),
        ),
        migrations.AddField(
            model_name='medicalconsultation',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.service'),
        ),
    ]
